name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    # This is a hack to deal with library version constraint syntax
    # difference between arduino-cli and arduino-lint. Repo syntax
    # is for arduino-lint, so library will show up in Library Manager.
    # Hack modifies library.properties to arduino-cli syntax, so CI
    # which uses arduino-cli will run.
    - name: <HACK> modify library.properties <HACK>
      run: sed -i 's/lvgl (=8.2.0)/lvgl@8.2.0/' library.properties

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py cpx_ada cpb clue pyportal

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit LittlevGL Glue Library"
      run: bash ci/doxy_gen_and_deploy.sh
